server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_library?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minIdle: 3
    maxActive: 30
    maxWait: 20000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    connectionInitSqls: SELETE 1
    filters: stat,wall,slf4j

  #处理时间
  jackson:
    date-format: yyyy-MM-dd

  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true

mybatis-plus:
  # 信息输出设置
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: "t_"

logging:
  level:
    root: info